services:
  mysql:
    container_name: mysql
    image: mysql:8.4.7
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: MeChat
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
      - mysql_files:/var/lib/mysql-files
      - mysql_log:/var/log/mysql
    restart: always

  redis:
    container_name: redis
    image: redis:7.4.2
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass redis
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:1.27-alpine
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  mysql_files:
  mysql_log:
  redis_data:
